### ISSUE TITLE
The SQL bind Dialog can not closed

### ISSUE THREAD

**Issue by ChenXiaoTemp** [naver/pinpoint#6621] opened 2020-03-20 12:37 UTC
#### Prerequisites

- [ ] I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
v2.0.1

#### Describe the bug
The sql bind dialog can not be closed after I open it.

#### What did you do to trigger the bug?
Steps to reproduce, for example:
1. use the agent to monitor a app with sql bind methods
2. View the transaction detail
3, Click the sql bind button

#### Expected behavior
After I view the sql bind detail, there should one button to close the dialog

#### Screenshots
<img width="1269" alt="屏幕快照 2020-03-20 下午8 29 38" src="https://user-images.githubusercontent.com/5827720/77164147-9bfa8700-6aea-11ea-999d-b6f157a5aba5.png">

**Comment by RoySRose** [comment] 2020-03-20 12:58
Hello, @ChenXiaoTemp  Thank you for the report
But, I've just tested with the latest snapshot. didn't find any problem with closing the dialog
As you can see there is 'x' button on the top right. 

![image](https://user-images.githubusercontent.com/20402016/77165435-a66e4e00-6af5-11ea-879c-15718b57e5aa.png)

Do you think you can check whether this is happening in Local only?

**Comment by linux0x5c** [comment] 2020-03-22 04:09
I have same problem,on 13 inch screen.

**Comment by RoySRose** [comment] 2020-03-24 06:32
@binDongKim 
care to take a look at this?

**Comment by binDongKim** [comment] 2020-03-24 07:34
@ChenXiaoTemp @linux0x5c
I wasn't able to find any issue about it on my local. Could you two provide your testing environment such as os, browser? Plus, I'd like you to check if any error has been marked on your browser console. If there has, I'd appreciate if you leave them in the comment as well. Thank you.

**Comment by ChenXiaoTemp** [comment] 2020-03-25 01:54
My browser is chrome 80.0.3987.149
My os is macOS 
Actually, I found only click some special button, it occurs, like following:
<img width="328" alt="屏幕快照 2020-03-25 上午9 46 57" src="https://user-images.githubusercontent.com/5827720/77493603-8edcef80-6e7e-11ea-89ff-2ee788225c90.png">


The close button exist on the right top, but it is very small and covered by the page border

**Comment by binDongKim** [comment] 2020-03-25 08:31
@ChenXiaoTemp 
The issue was caused by the incorrect setting of the dialog height, which is resolved by https://github.com/naver/pinpoint/pull/6637. Thanks for your report.

**Closed by binDongKim** 2020-03-25 08:31 UTC
