### ISSUE TITLE
pinpoint-web startup error ,help!

### ISSUE THREAD

**Issue by jack161641** [naver/pinpoint#3058] opened 2017-06-20 11:36 UTC
#### Description
catalina.out 

2017-06-20 19:16:37 [ERROR](o.a.h.h.s.o.a.z.ClientCnxn         ) from localhost-startStop-1-SendThread(localhost:2181)
java.lang.IllegalStateException: Can't overwrite cause with java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [org.apache.hadoop.hbase.shaded.org.apache.zookeeper.server.ZooTrace]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.
	at java.lang.Throwable.initCause(Throwable.java:457)
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1316)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1196)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1157)
	at org.apache.hadoop.hbase.shaded.org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1128)
Caused by: java.lang.ClassNotFoundException
	at org.apache.catalina.loader.WebappClassLoaderBase.checkStateForClassLoading(WebappClassLoaderBase.java:1315)

#### Environment
pinpoint-web 1.6.2
jdk "1.8.0_101"
hbase-1.2.6

**Comment by xbblq7n** [comment] 2017-06-22 13:04
I am also facing the same issue in starting up the pinpoint web. Getting the same erros as above.

Kindly help

**Comment by xbblq7n** [comment] 2017-06-22 13:08
@denzelsN Please help in resolving the webui issue. Thanks

**Comment by jack161641** [comment] 2017-06-23 02:01
@xbblq7n I resolve this case, copy jar file hbase-shaded-server-1.1.1.jar to lib tomcat directory, download url http://snacktrace.com/artifacts/org.apache.hbase/hbase-shaded-server/1.1.1/org.apache.hadoop.hbase.shaded.org.apache.zookeeper.server.ZooTrace,but I have another problem ,pinpoint web and pinpoint collect had both same error,follow:
21-Jun-2017 17:46:11.874 SEVERE [main] org.apache.catalina.startup.ContextConfig.processServletContainerInitializers Failed to detect ServletContainerInitiali
zers for context with name [/pinpoint-collector]
 java.io.IOException: java.lang.ClassNotFoundException: com.sun.jersey.server.impl.container.servlet.JerseyServletContainerInitializer
        at org.apache.catalina.startup.WebappServiceLoader.loadServices(WebappServiceLoader.java:192)
        at org.apache.catalina.startup.WebappServiceLoader.load(WebappServiceLoader.java:159)
        at org.apache.catalina.startup.ContextConfig.processServletContainerInitializers(ContextConfig.java:1624)
        at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1135)
        at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:775)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:299)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5095)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1107)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1841)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1019)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:409)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1551)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:284)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:424)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:367)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:976)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1439)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1429)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)

**Comment by xbblq7n** [comment] 2017-06-23 06:28
@jack161641 The error is not occuring in the logs now. But still the web-ui is not coming up for me. Can you please help on this

**Comment by xbblq7n** [comment] 2017-06-25 15:03
Hi,

Can you help on this please?

**Comment by Xylus** [comment] 2017-06-26 04:38
@xbblq7n What kind of error are you getting? Could you explain the issue with more detail?

**Comment by jack161641** [comment] 2017-06-26 10:27
@xbblq7n I recompile and build war packages from the GitHub,resolved this error

**Comment by xbblq7n** [comment] 2017-06-26 15:28
@Xylus i am not able to get the pinpoint ui when deploying the ui war file, 

Can you please help on that

**Comment by minwoo-jung** [comment] 2017-06-27 01:14
Show me the all log of pinpoint web.  Could explain the issue more detail?
ex) how does it look in web browser? response is 404 status or you can see main page.

**Comment by jack161641** [comment] 2017-06-27 06:47
@minwoo-jung can I use collect pull date from agent？

**Comment by xbblq7n** [comment] 2017-06-27 06:55
[weblogs.txt](https://github.com/naver/pinpoint/files/1104387/weblogs.txt)

Attached the logs. I am getting the 404 status.

I downloaded the war file and ran it in tomcat.

**Comment by xbblq7n** [comment] 2017-06-27 07:03
Steps i have done to setup the pinpoint. Please let me know if i am wrong some where.

 **HBASE**

HBase is the Hadoop database, a distributed, scalable, big data store. Download the HBase binary in to the linux machine

Before installing the HBase, Please make sure the JAVA is installed on that machine. Now, extract and install the HBase by using the below commands
gunzip -d hbase-1.3.1-bin.tar.gz
tar -xvf hbase-1.3.1-bin.tar
     2. Once installed, Set the JAVA_PATH 
export JAVA_HOME=/usr/java/jdk1.8.0_74
PATH=$PATH:$HOME/bin
PATH=$PATH:$JAVA_HOME/bin
PATH=$PATH:(HBase directory)/bin
    3. Now start the HBase by invoking the startup script placed in the bin directory
./start-hbase.sh
HBase is now started and it is up and running. Create the tables inside the Hbase

Whenever HBase is started up, it will store all the data under the /tmp directory. To change the location of the data written add the below in the conf/hbase-site.xml

Here i have chosen to write or create the table in the root/xbblq7n directory
<property>
    <name>hbase.rootdir</name>
    <value>file:///root/xbblq7n/hbase</value>
</property>
<property>
    <name>hbase.zookeeper.property.dataDir</name>
    <value>/root/xbblq7n/zookeeper</value>
</property>
   4. To create the tables, we need to download the pinpoint.zip and then unzip it. Once it is unzipped, Execute the below command to create the tables.
/root/hbase-1.3.1/bin/hbase shell /root/pinpoint-master/hbase/scripts/hbase-create.hbase
(HBase directory)/bin/hbase shell (PinPoint directory)/hbase/scripts/hbase-create.hbase

Now the tables are created and can be viewed in the following URL:
http://localhost:16010/master-status

**Pinpoint Collector**

Step 1: Download the tomcat 8.5
Step 2: Go to the bin directory and invoke ./startup.sh to start the tomcat process
Step 3: Download the collector war file in to the webapps folder of tomcat. Since the tomcat is up and running, war file will deployed automatically\

**Pinpoint Web**

Step 1: Download the Pinpoint web war file in to the webapps folder of tomcat. Since the tomcat is up and running, war file will deployed automatically.
Step 2: Rename the pinpoint-web-1.6.1.war as ROOT.war. 
Now you will be able to see the Pinpoint UI in the default tomcat port(8080).

**Comment by jack161641** [comment] 2017-06-27 08:01
@xbblq7n export JAVA_HOME=/usr/java/jdk1.8.0_74 ,use idk 1.7 home

**Comment by minwoo-jung** [comment] 2017-06-27 08:11
@xbblq7n You should see error log in weblogs.txt file.

**Comment by minwoo-jung** [comment] 2017-06-27 08:14
@jack161641 I do not know what you mean.
```
@minwoo-jung can I use collect pull date from agent？
```

**Comment by jack161641** [comment] 2017-06-27 08:17
@minwoo-jung What I mean is how to use collect to get agent data, from the collect connection to the agent

**Comment by minwoo-jung** [comment] 2017-06-27 08:33
@jack161641 If you want to see agent data without pinpoint web, you can use and see agent data by connecting hbase.

**Comment by jack161641** [comment] 2017-06-27 08:53
@minwoo-jung I mean because of the reasons for the firewall, my agent can not access collect, but collect can access agent, the system default data is pushed from the agent to collect, but I hope to collect from the collect agent data

**Comment by minwoo-jung** [comment] 2017-06-27 09:13
We don't call 'collect' with name of  pinpoint collector.
Pinpoint don't provide function for your question. We don't recommend that collector pull agent data for various reasons.

**Comment by GilbertDai** [comment] 2017-06-27 09:50
@minwoo-jung  for what reasons ,Pinpoint do not support  collector pull agent data? 
( we deploy collector in our internal network , and agent is on the cloud, but collector service port is blocked by firewall , so we consider whether  collector can  pull  agent data) thanks。

**Comment by xbblq7n** [comment] 2017-06-27 10:39
@xbblq7n You should see error log in weblogs.txt file.

@minwoo-jung i am not getting the above comment you mentioned. Can you please elaborate

**Comment by minwoo-jung** [comment] 2017-06-28 01:00
@xbblq7n 
Exception message in weblogs.txt file.
```
2017-06-27 02:51:35 [ERROR](o.s.w.c.ContextLoader              ) Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'activeTraceService' defined in file [/root/apache-tomcat-8.0.44/webapps/pinpoint-web-1.6.2/WEB-INF/classes/com/navercorp/pinpoint/web/service/stat/ActiveTraceService.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [com.navercorp.pinpoint.web.dao.stat.ActiveTraceDao]: : Error creating bean with name 'activeTraceDaoFactory': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: AgentStat, AgentStatV2 tables do not exist; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'activeTraceDaoFactory': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: AgentStat, AgentStatV2 tables do not exist
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1137)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1040)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:762)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:434)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4853)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5314)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:729)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1816)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'activeTraceDaoFactory': FactoryBean threw exception on object creation; nested exception is java.lang.IllegalStateException: AgentStat, AgentStatV2 tables do not exist
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:175)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1525)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:251)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
        ... 28 more
Caused by: java.lang.IllegalStateException: AgentStat, AgentStatV2 tables do not exist
        at com.navercorp.pinpoint.web.dao.hbase.stat.AgentStatDaoFactory.getDao(AgentStatDaoFactory.java:88)
        at com.navercorp.pinpoint.web.dao.hbase.stat.AgentStatDaoFactory$ActiveTraceDaoFactory.getObject(AgentStatDaoFactory.java:248)
        at com.navercorp.pinpoint.web.dao.hbase.stat.AgentStatDaoFactory$ActiveTraceDaoFactory.getObject(AgentStatDaoFactory.java:233)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
        ... 37 more`
```

did you create hbase table?

**Comment by minwoo-jung** [comment] 2017-06-28 01:37
@GilbertDai

Because Collector server process data for too many agent server, It is difficult to pull data of many agent.
If Collector pull data of agent, collector need to check many status connection and transmission status of data.
For example, WAS(web application server) listen connection from agent and accept client data.

Could change port of collector server to permitted at firewall?
You can change listen Port of collector server.

**pinpoint-collector.properties**
```
collector.tcpListenPort=9994
collector.udpStatListenPort=9995
collector.udpSpanListenPort=9996
```

**Comment by GilbertDai** [comment] 2017-06-28 01:53
@minwoo-jung  thanks for your answer, by the way,what the detail function of port 9994, 9995,9996

**Comment by minwoo-jung** [comment] 2017-06-28 02:48
We use tcp to send meta data and agent info and use udp to send stat and transaction data.

**Comment by GilbertDai** [comment] 2017-06-28 03:52
@minwoo-jung   we have a app-A ,A is  deployed on cloud,A will invoke app-B, B is deployed in our internal network , now collector and hbase is in our internal network, we use tomcat and suppose A 
deal with 10，000 transactions per day. consider the internal network bandwidth(suppose 200M), If  the agent of A push data to collector ,is ok?  thanks.

**Comment by xbblq7n** [comment] 2017-06-28 06:38
@minwoo-jung I have the Hbase up and running.

**Comment by minwoo-jung** [comment] 2017-06-28 07:17
@GilbertDai
You could see for yourself. Network utilization depend on metadata count size, method call count in one transaction etc.
For reference
Try to raise sampling rate little by little.

pinpoint.config file in agent package
```
# 1 out of n transactions will be sampled where n is the rate. (20: 5%) 
37 profiler.sampling.rate=20 

```

**Comment by minwoo-jung** [comment] 2017-06-28 07:19
@xbblq7n

This exception message.
**Caused by: java.lang.IllegalStateException: AgentStat, AgentStatV2 tables do not exist**

did you check create table in your hbase server?

**Comment by xbblq7n** [comment] 2017-06-28 07:41
@minwoo-jung yes i have the tables created in the Hbase.

**Comment by minwoo-jung** [comment] 2017-06-28 08:35
@xbblq7n
check hbase config(ip, port) in pinpoint web.

**Comment by xbblq7n** [comment] 2017-06-28 09:59
@minwoo-jung 
Below is my config 
hbase.client.host=localhost
hbase.client.port=2181

# hbase default:/hbase
hbase.zookeeper.znode.parent=/hbase

# hbase timeout option==================================================================================
# hbase default:true
hbase.ipc.client.tcpnodelay=true
# hbase default:60000
hbase.rpc.timeout=10000
# hbase default:Integer.MAX_VALUE
hbase.client.operation.timeout=10000

# hbase socket read timeout. default: 200000
hbase.ipc.client.socket.timeout.read=20000
# socket write timeout. hbase default: 600000
hbase.ipc.client.socket.timeout.write=30000

#==================================================================================
# hbase client thread pool option
hbase.client.thread.max=64
hbase.client.threadPool.queueSize=5120
# prestartAllCoreThreads
hbase.client.threadPool.prestart=false

#==================================================================================
# hbase parallel scan options
hbase.client.parallel.scan.enable=true
hbase.client.parallel.scan.maxthreads=64
hbase.client.parallel.scan.maxthreadsperscan=16

**Comment by xbblq7n** [comment] 2017-06-28 10:06
@minwoo-jung 

Also one more thing, today i download the code from the github and the i used the below command to run the pinpoint as docker
**Command:**
docker-compose up

sql started to download but after that hbase was not installed. below error is thrown

[root@r01052n0v pinpoint-master]# docker-compose up
Pulling pinpoint-mysql (mysql:5.7)...
5.7: Pulling from library/mysql
9f0706ba7422: Pull complete
2290e155d2d0: Pull complete
547981b8269f: Pull complete
2c9d42ed2f48: Pull complete
55e3122f1297: Pull complete
abc10bd84060: Pull complete
c0a5ce64f2b0: Pull complete
c4595eab8e90: Pull complete
098988cead35: Pull complete
300ca5fa5eea: Pull complete
43fdc4e3e690: Pull complete
Digest: sha256:d178dffba8d81afedc251498e227607934636e06228ac63d58b72f9e9ec271a6
Status: Downloaded newer image for mysql:5.7
Pulling pinpoint-hbase (naver/pinpoint-hbase:1.7.0-SNAPSHOT)...
ERROR: repository naver/pinpoint-hbase not found: does not exist or no pull access

**Comment by xbblq7n** [comment] 2017-06-29 06:38
@minwoo-jung Can you please help me on this?

**Comment by minwoo-jung** [comment] 2017-06-29 07:27
@xbblq7n
See hbase url and port configuration in hbase.
Don't use SNAPSHOT version. I reecommend to use 1.6.2 version

**Comment by xbblq7n** [comment] 2017-06-29 07:54
@minwoo-jung 

Where to find out the base url and port configuration in hbase?

Also to run the Pinpoint as a docker. do we have any official images?

**Comment by xbblq7n** [comment] 2017-06-29 07:56
@minwoo-jung 

Also i see the Hbase is up and running in URL http://*******:16010/master-status

**Comment by xbblq7n** [comment] 2017-06-29 10:58
[WebLogs.txt](https://github.com/naver/pinpoint/files/1111744/WebLogs.txt)

@minwoo-jung 

Attaching the logs of the Web. Still the UI shows 404 error. I am not able view it. Please advise

**Comment by minwoo-jung** [comment] 2017-06-30 01:13
@xbblq7n
I think that you need to underatand tomcat and how to deploy war. Please search web or read tomcat manual.

**Comment by xbblq7n** [comment] 2017-07-04 07:16
@minwoo-jung I will look in to it.

Can you please tell me if we have pinpoint images to run as docker container.

**Comment by xbblq7n** [comment] 2017-07-05 06:42
@minwoo-jung Can you please help on this. Do we have pinpoint images to run as docker container?

**Comment by xbblq7n** [comment] 2017-07-07 07:02
@minwoo-jung Can you please update on this?

**Comment by minwoo-jung** [comment] 2017-07-13 02:52
@xbblq7n
I'm sorry it has taken so long to reply to your question
We don't provide docker image. But We guide using scipt( [docker-compose.yml](https://github.com/naver/pinpoint/blob/1.6.2/docker-compose.yml) ).

**Closed** 2017-07-13 06:46 UTC
Labels: question
