### ISSUE TITLE
is it a bug for mongodb?

### ISSUE THREAD

**Issue by shotgun88** [naver/pinpoint#5144] opened 2019-01-17 03:16 UTC
i can detective mysql、redis but not mongodb.
could u explain why?thank u a lot
![image](https://user-images.githubusercontent.com/42365630/51293304-4ab7b900-1a49-11e9-863d-5d151aaa62a3.png)

**Comment by shotgun88** [comment] 2019-01-17 06:09
yes,i am using mongodb java driver.
and also i am using the latest version 1.8.1 of pinpoint.
so i see that the lastest version can detect mongodb,but actually it seems not work out.
could u please let me know when will be fixed up?

**Comment by RoySRose** [comment] 2019-01-17 06:39
@shotgun88 
It's planned to be released in 1.8.2
I don't think the bug effects the detection. What you are facing might be something else.

here is the fixed version of agent if you'd like to try.
It would be great if you can help with the testing.
https://github.com/RoySRose/pinpoint/releases/download/untagged-915d6cffc5b6859213f9/pinpoint-agent-1.8.2.jar

**Comment by shotgun88** [comment] 2019-01-17 06:41
Sorry,the link was wrong?
![image](https://user-images.githubusercontent.com/42365630/51300180-f53dd500-1a65-11e9-81a8-3a0ee747bf68.png)

**Comment by shotgun88** [comment] 2019-01-17 07:02
i got the jar files
![image](https://user-images.githubusercontent.com/42365630/51301062-dab92b00-1a68-11e9-9748-96e31fa6cfa1.png)

but please let me know where i put it on?

**Comment by RoySRose** [comment] 2019-01-17 07:11
Sorry, I didn't make it public.

https://github.com/RoySRose/pinpoint/releases/tag/temp

also changed the download just like an ordinary release.
you can replace with 1.8.1

**Comment by RoySRose** [comment] 2019-01-17 07:11
@shotgun88 
let me know if you have any updates

**Comment by shotgun88** [comment] 2019-01-17 07:58
i unzip files and renew configuration,but my application did turn up
![image](https://user-images.githubusercontent.com/42365630/51303393-2e7b4280-1a70-11e9-9cd3-a570b9d3efe2.png)
![image](https://user-images.githubusercontent.com/42365630/51303406-3aff9b00-1a70-11e9-9629-f8f4cdbeec50.png)
![image](https://user-images.githubusercontent.com/42365630/51303464-64202b80-1a70-11e9-9dab-fad627e12261.png)
and is it mongo's version problem before?beacause my mongodb's version is 3.0.15 that lead to cant not able to detected?

**Comment by shotgun88** [comment] 2019-01-17 08:20
also i change mongodb's version is 3.6.7,it also cant not able to detected
![image](https://user-images.githubusercontent.com/42365630/51304528-6637b980-1a73-11e9-954c-55f416646af2.png)
it seems mongo's plugin didnt work out that cant not able to be detected
![image](https://user-images.githubusercontent.com/42365630/51304712-d6ded600-1a73-11e9-9c04-bdff45832a08.png)

**Comment by RoySRose** [comment] 2019-01-17 08:46
@shotgun88 

The version of Mongodb itself has nothing to do with detecting.
plugins should be 1.8.2-SNAPSHOT, not 1.8.1
maybe 1.8.2-SNAPSHOT is not applied. please check the version again

**Comment by RoySRose** [comment] 2019-01-17 08:50
@shotgun88 
What is the version of Pinpoint-Collector and Pinpoint-Web?

**Comment by shotgun88** [comment] 2019-01-17 09:09
for previous 1.8.2-SNAPSHOT can not able to use,even can not able to turn up my application.
so i change back to 1.8.1 which the latest version for release 1.8.1 of collect、web
but my question is why can not to detect mongodb?even i change mongo's version to 3.6.7(i guess is mongo's version problem before)
now i think it's maybe somewhere to block the detecting mongo,it didnt make sense why i can detect mysql、redis not mongo
could u explain why this happen?

**Comment by RoySRose** [comment] 2019-01-17 09:15
I think, with 
Pinpoint-Agent : 1.8.2-SNAPSHOT
Pinpoint-Collector : 1.8.1
Pinpoint-Web : 1.8.1
There shouldn't be any problem.

I can't point out the reason why detecting mongodb fails in your environment.
I have insufficient information on your environment to guess the reason for detection problem.

**Comment by shotgun88** [comment] 2019-01-17 09:18
maybe i can provide some information to pick up the probelm.
what do you want to show you something else?

**Comment by shotgun88** [comment] 2019-01-17 09:45
i just did what u told,but it still not work out
![image](https://user-images.githubusercontent.com/42365630/51309447-6342c600-1a7f-11e9-8964-65328c9be564.png)
so what can i provide some clues to u in next step?

**Comment by RoySRose** [comment] 2019-01-17 09:55
@shotgun88 
I think we can start from here.

1. What the version of mongodb-java-driver?
2. change the log level to `debug`. And please check the log when your application start-up,
and check if there isn't any error around it. It should be around the log as below
 ```text
2019-01-17 18:37:35 [DEBUG](c.n.p.p.i.c.URLClassLoaderHandler  :100) add Jar:file:/Users/user/IdeaProjects/pinpoint/agent/target/pinpoint-agent-1.8.2-SNAPSHOT/plugin/pinpoint-mongodb-driver-plugin-1.8.2-SNAPSHOT.jar
2019-01-17 18:37:36 [DEBUG](c.n.p.p.o.AutoBindingObjectFactory :95 ) Create instance by constructor public com.navercorp.pinpoint.plugin.mongo.interceptor.MongoDriverGetDatabaseInterceptor(com.navercorp.pinpoint.bootstrap.context.TraceContext,com.navercorp.pinpoint.bootstrap.context.MethodDescriptor), with arguments [com.navercorp.pinpoint.profiler.context.DefaultTraceContext@7f34a967, {className=com.mongodb.MongoClient, methodName=getDatabase, parameterTypes=[java.lang.String], parameterVariableName=[databaseName], parameterDescriptor=(java.lang.String databaseName), apiDescriptor=com.mongodb.MongoClient.getDatabase(java.lang.String databaseName), lineNumber=550, apiId=145, fullName=com.mongodb.MongoClient.getDatabase(java.lang.String databaseName):550, type=0}]
2019-01-17 18:37:36 [DEBUG](c.n.p.p.BaseClassFileTransformer   :47 ) [transform] classLoader:ParallelWebappClassLoader
```
3. Please check the log if there isn't any errors.
4. Check Collector log if collector has received mongodb data from the agent. it should be something like below.(below log means mongodb data has been received from the Pinpoint-Agent
```text
2019-01-17 18:52:57 [DEBUG](c.n.p.c.h.t.ThriftSpanHandler      :67 ) Received SPAN=TSpan(agentId:roy-app, applicationName:roy-app, agentStartTime:1547718733242, transactionId:00 01 BA DB E6 D9 85 2D 05, spanId:-8960468173174276706, parentSpanId:-1, startTime:1547718777366, elapsed:328, rpc:/mongodb/filterGEO.pinpoint, serviceType:1010, endPoint:localhost:9090, remoteAddr:0:0:0:0:0:0:0:1, annotations:[TAnnotation(key:46, value:<TAnnotationValue intValue:200>)], flag:0, err:0, spanEventList:[TSpanEvent(sequence:4, startElapsed:175, endElapsed:59, serviceType:2651, endPoint:10.106.157.82:27017, annotations:[TAnnotation(key:151, value:<TAnnotationValue stringValue:customers>), TAnnotation(key:152, value:<TAnnotationValue stringValue:secondary>), TAnnotation(key:150, value:<TAnnotationValue stringStringValue:TStringStringValue(stringValue1:{ "loc" : { "$geoWithin" : { "$polygon" : [["?", "?"], ["?", "?"], ["?", "?"], ["?", "?"]] } } }, stringValue2:28.56402,79.93652,27.27569,26.16394,42.69404,20.02808,48.61541,51.37207)>)], depth:5, destinationId:myMongoDb, apiId:361), TSpanEvent(sequence:3, startElapsed:62, endElapsed:172, serviceType:5071, depth:4, apiId:35), TSpanEvent(sequence:2, startElapsed:10, endElapsed:288, serviceType:5071, depth:3, apiId:263), TSpanEvent(sequence:1, startElapsed:2, endElapsed:326, serviceType:5051, depth:2, apiId:-3), TSpanEvent(sequence:0, startElapsed:1, endElapsed:327, serviceType:1011, depth:1, apiId:-2)], parentApplicationType:0, apiId:2, applicationServiceType:1010, loggingTransactionInfo:0)
```
5. Check Hbase if there is any data.

**Comment by shotgun88** [comment] 2019-01-18 02:46
i am using the version of mongodb-java-driver is 3.2.2
![image](https://user-images.githubusercontent.com/42365630/51361492-f96ffe00-1b0a-11e9-9dd6-a0df839e7c2d.png)
and i've checked my application's log appears pinpoints detect mongodb's information,but seems not as u mention,please see below
![image](https://user-images.githubusercontent.com/42365630/51361630-8adf7000-1b0b-11e9-9815-25d1b330c30a.png)
![image](https://user-images.githubusercontent.com/42365630/51361668-aa769880-1b0b-11e9-97a8-741f467b1cb5.png)
besides,i cant find out any information about mongodb in colletor's log
![image](https://user-images.githubusercontent.com/42365630/51362371-40abbe00-1b0e-11e9-8fd8-4f9344c1cdac.png)

**Comment by RoySRose** [comment] 2019-01-18 04:03
@shotgun88 
if you can't find any info about mongodb in Pinpoint-Collector's log. 
try to find it in Pinpoint-Agent's log first.(change the log level to DEBUG, before running it)

**Comment by shotgun88** [comment] 2019-01-18 06:14
can you tell me where to set up log's level for Pinpoint-Agent?

**Comment by shotgun88** [comment] 2019-01-18 06:46
here is agent's log,please check as below:
![image](https://user-images.githubusercontent.com/42365630/51369792-d3a92000-1b2f-11e9-9889-4c922f7ec9bc.png)

**Comment by shotgun88** [comment] 2019-01-18 07:02
it seems the agent just init mongo's configuration,but not send mongo's data information to collect,please see agent's sending data as below:
![image](https://user-images.githubusercontent.com/42365630/51370235-639b9980-1b31-11e9-8dad-ed41640a82fa.png)

please see collect's log as below:
![image](https://user-images.githubusercontent.com/42365630/51370413-f50b0b80-1b31-11e9-9c68-cb0e2435768a.png)
![image](https://user-images.githubusercontent.com/42365630/51370423-048a5480-1b32-11e9-8db5-e527cd7b14b3.png)

**Comment by RoySRose** [comment] 2019-01-18 07:06
@shotgun88 were there any transaction flow to mongodb? by mongodb java driver?

**Comment by shotgun88** [comment] 2019-01-18 07:11
maybe insert some data to mongodb when i just operated on application.
but no mongodb's information to send even comes up in log

**Comment by RoySRose** [comment] 2019-01-18 07:55
1. please check if plugin is disabled in pinpoint.config file
```text
profiler.mongo=true
profiler.mongo.collectjson=true
profiler.mongo.tracebsonbindvalue=true
```

2. can you show me your code? the on where you execute `insert`.

**Comment by RoySRose** [comment] 2019-01-23 01:13
@shotgun88 
any updates?

**Comment by shotgun88** [comment] 2019-01-23 01:52
i've checked agent's mongo configuration was open as below:
![image](https://user-images.githubusercontent.com/42365630/51577265-3154b800-1ef4-11e9-8b88-720eded2a5dd.png)
and i try many times to check everywhere,looks like all fine,but still can not able to detected mongodb.i have no idea where to goes wrong.....

**Comment by RoySRose** [comment] 2019-01-23 02:14
@shotgun88 

can I have a small look at your application code. where you CRUD.
for example  
```java
collection.insertOne()
```

**Comment by shotgun88** [comment] 2019-01-23 03:14
please see below:
![image](https://user-images.githubusercontent.com/42365630/51580608-0e300580-1f00-11e9-9112-1c1cb4630647.png)

**Comment by RoySRose** [comment] 2019-01-23 04:39
@shotgun88 
how did you get your mongoDatabase() in the first place?
by mongoClient.getDatabase method?

**Comment by shotgun88** [comment] 2019-01-24 01:47
please see below:
![image](https://user-images.githubusercontent.com/42365630/51648813-100bce80-1fbd-11e9-9676-e47d45cc9c15.png)

**Comment by RoySRose** [comment] 2019-01-24 06:11
@shotgun88 
the plugin doesn't support spring-data-mongodb yet.
I think this will be the reason

**Comment by RoySRose** [comment] 2019-01-25 00:39
@shotgun88 
I've created a simple application wit spring-data-mongo, and checked it work.
I'll test few more things and let you know the results

**Comment by RoySRose** [comment] 2019-01-25 08:46
Hello, @shotgun88 

I've checked with spring-data, spring-boot. All came up fine.
I'd like to reproduce what you are experiencing, but have no clue.

If you can send me the full DEBUG log of Agent, Collector, Web. I'll take a look.

Feel free to reopen this issue if you'd like.

**Closed by RoySRose** 2019-01-25 08:46 UTC

**Comment by shotgun88** [comment] 2019-01-29 08:10
Hi RoySRose
please check logs as below:

[mbox144-pinpoint.log](https://github.com/naver/pinpoint/files/2806585/mbox144-pinpoint.log)
[service144-pinpoint.log](https://github.com/naver/pinpoint/files/2806586/service144-pinpoint.log)
[stat.log](https://github.com/naver/pinpoint/files/2806587/stat.log)
[catalina.txt](https://github.com/naver/pinpoint/files/2806591/catalina.txt)

**Comment by RoySRose** [comment] 2019-01-30 01:45
@shotgun88

**Comment by RoySRose** [comment] 2019-01-30 01:49
Hello, @shotgun88 
I've looked at the logs. couldn't find anything special. 
I've assumed how you're using mongodb-java-driver with piece of your code.
and tried to regenerate the problem. But couldn't, I've checked the plugin working with spring-data-mongo (with and without) spring-boot.

fixed plugin has been released, why don't you try with [v1.8.2-RC1](https://github.com/naver/pinpoint/releases/tag/1.8.2-RC1)

**Comment by shotgun88** [comment] 2019-01-30 04:01
i am sorry to let u know that is not aevalible for v1.8.2-RC1
it is still can not work it out for mongodb
please see detail as below:
![image](https://user-images.githubusercontent.com/42365630/51957088-3500b580-2485-11e9-9dba-40d934bcd3fa.png)
![image](https://user-images.githubusercontent.com/42365630/51957102-42b63b00-2485-11e9-8942-9ed9a7bf5f68.png)
[catalina.txt](https://github.com/naver/pinpoint/files/2810790/catalina.txt)
[Uploading stat.log…]()
[Uploading mbox144-pinpoint.log…]()
[Uploading service144-pinpoint.log…]()

**Comment by shotgun88** [comment] 2019-01-30 04:04
[mbox144-pinpoint.log](https://github.com/naver/pinpoint/files/2810801/mbox144-pinpoint.log)
[service144-pinpoint.log](https://github.com/naver/pinpoint/files/2810802/service144-pinpoint.log)
[stat.log](https://github.com/naver/pinpoint/files/2810803/stat.log)

**Comment by shotgun88** [comment] 2019-01-30 06:10
Hi RoySRose @RoySRose 
can i provide the application to u guys to see what exactly happen(why can not able to detect mongodb),please send me e-mail address

**Comment by RoySRose** [comment] 2019-01-30 06:38
oh~ really? of course~ maybe this thread is getting too long.
provide me with the application on [here](roy.kim@navercorp.com)

**Comment by shotgun88** [comment] 2019-01-30 06:55
Hi RoySRose
that email address was not able to access which blocked email send me back(i've been try twice).
have u got any email address?

**Comment by RoySRose** [comment] 2019-01-30 06:57
sungwook0115.kim@gmail.com 
would to the trick.

**Comment by shotgun88** [comment] 2019-01-30 07:56
please see below with attackment

[application.zip](https://github.com/naver/pinpoint/files/2811389/application.zip)

**Comment by RoySRose** [comment] 2019-01-30 08:07
@shotgun88 

how should I set this application.zip to work?
any advice?

**Comment by shotgun88** [comment] 2019-01-31 01:59
@RoySRose 
yes,i think it sign up mongo and dubbo configuration on that conf/application.properties in your enviroment.
and run sh bin/start.sh
finally watch logs show up the application was start up with finish detail then it will be all things right
as below:
![image](https://user-images.githubusercontent.com/42365630/52025306-d3048680-253e-11e9-89c1-83fe4a9c1bcc.png)

**Comment by RoySRose** [comment] 2019-01-31 05:39
I've set mongodb and dubbo config. also started a zookeeper with docker for dubbo.

and now I get...
I can't find where 10.66.96.84 came from since there isn't such address in the properties.
maybe it's in the source code. 

guessing with the log. it's trying to start up a server.
Since I can't see the source code. I can't assume what it can be.

![image](https://user-images.githubusercontent.com/20402016/52032752-af086b80-2565-11e9-9ece-5ea759361f0e.png)

**Comment by shotgun88** [comment] 2019-01-31 06:07
counld u please send me some information about configuation?

**Comment by RoySRose** [comment] 2019-01-31 07:37
this is it.
I've started up a zookeeper on localhost:2181
mongodb also taken care of.
that's all I've done

```text
# dubbo config
dubbo.application=poggyio-mbox
dubbo.protocol=dubbo
dubbo.protocol.host=localhost
dubbo.protocol.port=20804
dubbo.protocol.payload=33554432
dubbo.registry=127.0.0.1:2181
dubbo.logger=slf4j
dubbo.qos.enable=false
dubbo.qos.port=22224

# mongodb config
#mongodb.host=10.106.157.82
#mongodb.port=27017
mongodb.dbname=poggyio
mongodb.username=
mongodb.password=
mongodb.write-concern=SAFE
mongodb.authentication.dbname=
mongodb.replica-set=localhost:27017
mongodb.credentials=

mongodb.options.connectionPerHost=64
mongodb.options.connectionTimeout=3000
```

**Comment by shotgun88** [comment] 2019-02-01 02:53
have you tried to singh up dubbo.registry=(exactly IP address not 127.0.0.1):2181?
and mongodb.replica-set=(exactly IP address not localhost):27017?

**Comment by RoySRose** [comment] 2019-02-01 07:02
I've installed mongodb locally. So I don't think there will be problem with using 127.0.0.1 or localhost for mongodb config. (and no connection error pops up anyway).

for dubbo.registry. I'm not sure what needs to be run exactly. But so far I've found out is that it's zookeeper. So, I've run a docker image of zookeeper locally. 

Last of all, the error log. I've shown you, points to 10.66.96.84:20804. whatever it is...

**Comment by swift1911** [comment] 2019-02-14 10:00
@RoySRose In my test with v1.8.2 , it shows unknown db instead of mongodb,my mongodb driver version is 
```
<dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>3.7.1</version>
        </dependency>
```
![image](https://user-images.githubusercontent.com/9301003/52779037-54513280-3082-11e9-8844-5a9eca1031c5.png)
this is collector log:
```
2019-02-14 09:51:31 [INFO ](.n.p.c.h.t.ThriftApiMetaDataHandler) Received ApiMetaData=TApiMetaData(agentId:10.12.36.5, agentStartTime:1550137783470, apiId:312, apiInfo:com.mongodb.client.internal.MongoCollectionImpl.dropIndexes(com.mongodb.session.ClientSession clientSession), line:819, type:0)


2019-02-14 09:51:31 [INFO ](.n.p.c.h.t.ThriftApiMetaDataHandler) Received ApiMetaData=TApiMetaData(agentId:10.12.36.5, agentStartTime:1550137783470, apiId:-313, apiInfo:com.mongodb.client.internal.MongoCollectionImpl.dropIndexes(com.mongodb.client.model.DropIndexOptions dropIndexOptions), line:825, type:0)


2019-02-14 09:51:31 [DEBUG](c.n.p.c.d.h.HbaseApiMetaDataDao    ) insert:ApiMetaDataBo{agentId='10.12.36.5', startTime=1550137783470, apiId=-312, apiInfo='com.mongodb.client.internal.MongoCollectionImpl.dropIndexes()', lineNumber=814, methodTypeEnum=DEFAULT}


2019-02-14 09:51:31 [DEBUG](c.n.p.c.d.h.HbaseApiMetaDataDao    ) insert:ApiMetaDataBo{agentId='10.12.36.5', startTime=1550137783470, apiId=-313, apiInfo='com.mongodb.client.internal.MongoCollectionImpl.dropIndexes(com.mongodb.client.model.DropIndexOptions dropIndexOptions)', lineNumber=825, methodTypeEnum=DEFAULT}


2019-02-14 09:51:31 [DEBUG](c.n.p.c.d.h.HbaseApiMetaDataDao    ) insert:ApiMetaDataBo{agentId='10.12.36.5', startTime=1550137783470, apiId=312, apiInfo='com.mongodb.client.internal.MongoCollectionImpl.dropIndexes(com.mongodb.session.ClientSession clientSession)', lineNumber=819, methodTypeEnum=DEFAULT}


2019-02-14 09:51:31 [INFO ](.n.p.c.h.t.ThriftApiMetaDataHandler) Received ApiMetaData=TApiMetaData(agentId:10.12.36.5, agentStartTime:1550137783470, apiId:313, apiInfo:com.mongodb.client.internal.MongoCollectionImpl.dropIndexes(com.mongodb.session.ClientSession clientSession, com.mongodb.client.model.DropIndexOptions dropIndexOptions), line:830, type:0)


2019-02-14 09:51:31 [DEBUG](c.n.p.c.d.h.HbaseApiMetaDataDao    ) insert:ApiMetaDataBo{agentId='10.12.36.5', startTime=1550137783470, apiId=313, apiInfo='com.mongodb.client.internal.MongoCollectionImpl.dropIndexes(com.mongodb.session.ClientSession clientSession, com.mongodb.client.model.DropIndexOptions dropIndexOptions)', lineNumber=830, methodTypeEnum=DEFAULT}


2019-02-14 09:51:31 [INFO ](.n.p.c.h.t.ThriftApiMetaDataHandler) Received ApiMetaData=TApiMetaData(agentId:10.12.36.5, agentStartTime:1550137783470, apiId:-314, apiInfo:com.mongodb.client.internal.MongoCollectionImpl.withReadPreference(com.mongodb.ReadPreference readPreference), line:149, type:0)


2019-02-14 09:51:31 [DEBUG](c.n.p.c.d.h.HbaseApiMetaDataDao    ) insert:ApiMetaDataBo{agentId='10.12.36.5', startTime=1550137783470, apiId=-314, apiInfo='com.mongodb.client.internal.MongoCollectionImpl.withReadPreference(com.mongodb.ReadPreference readPreference)', lineNumber=149, methodTypeEnum=DEFAULT}


2019-02-14 09:51:31 [INFO ](.n.p.c.h.t.ThriftApiMetaDataHandler) Received ApiMetaData=TApiMetaData(agentId:10.12.36.5, agentStartTime:1550137783470, apiId:314, apiInfo:com.mongodb.client.internal.MongoCollectionImpl.withWriteConcern(com.mongodb.WriteConcern writeConcern), line:155, type:0)


2019-02-14 09:51:31 [DEBUG](c.n.p.c.d.h.HbaseApiMetaDataDao    ) insert:ApiMetaDataBo{agentId='10.12.36.5', startTime=1550137783470, apiId=314, apiInfo='com.mongodb.client.internal.MongoCollectionImpl.withWriteConcern(com.mongodb.WriteConcern writeConcern)', lineNumber=155, methodTypeEnum=DEFAULT}
```

**Comment by RoySRose** [comment] 2019-02-14 10:14
Hello, @swift1911 

I've tested with few applications and worked fine. Couldn't reproduce any of the problems.
Have you tried with the official release of v1.8.2?

how does your application com.mongodb.MongoClient ?

**Comment by jiazhong520** [comment] 2019-09-24 04:21
My version is 1.8.5, but I can't show that everything else in mongodDB can be displayed properly. That's too bad.

**Comment by RoySRose** [comment] 2019-09-25 02:12
plugin doesn't support for certain Mongodb java driver versions yet.
Take a look at below issues.

https://github.com/naver/pinpoint/pull/5435
https://github.com/naver/pinpoint/issues/5578

**Comment by PIYUSHRAJ24** [comment] 2023-06-13 08:33
Hi All,
I am also facing the same issue. I tell you all the details. I am using spring boot application and I have started monitoring it but the inter-connected components like mongodb and elasticsearch is not showing in servermap both the components are running on different servers and main application are running on different server. Actually I am very new to use  pinpoint-apm so please help me. how can i fix it? and what configuration i need to do in which configuration file. 

Thanks

**Comment by Avi-2509** [comment] 2024-02-16 12:30
Hi all, 
I am also facing the same issue, able to detect mysql, redis but not es and mongodb on pinpoint, also no error in collector and on agent side.
