### ISSUE TITLE
RabbitMQConsumeInterceptor NullPointerException

### ISSUE THREAD

**Issue by geekMessi** [naver/pinpoint#3818] opened 2018-02-10 02:27 UTC
#### Description
**RabbitMQConsumeInterceptor cause NullPointerException**
* [ WARN ] (.p.p.r.i.RabbitMQConsumeInterceptor) BEFORE. Caused:null
java.lang.NullPointerException
	at com.navercorp.pinpoint.plugin.rabbitmq.interceptor.RabbitMQConsumeInterceptor.createTrace(RabbitMQConsumeInterceptor.java:46)
	at com.navercorp.pinpoint.bootstrap.interceptor.SpanSimpleAroundInterceptor.before(SpanSimpleAroundInterceptor.java:51)

#### Environment

* Pinpoint version: 1.7.2-SNAPSHOT
* OS, WAS, affected library, etc: WAS
* Additional details (e.g. how your collector/web is set up):

**Comment by Xylus** [comment] 2018-02-12 05:23
Hi @geekMessi 
Looks like **AMQP.BasicProperties** can be null for empty headers.
(ping @jiaqifeng)

**Comment by jiaqifeng** [comment] 2018-02-13 02:20
@geekMessi @Xylus Yes, it seems hdeader is null. Since I am in vacation for China spring about a week I will fix this issue a little later. While since header is null, the message sender was not run with pinpoint agent, the this bug will just cause the lost of trace in consumer side, but will not affect the consumer to handle the message correctly. So in most case this exception is harmless.

**Comment by Xylus** [comment] 2018-02-13 02:39
@jiaqifeng Perfect, thanks :)

**Comment by jiaqifeng** [comment] 2018-03-05 03:21
@geekMessi @Xylus 
PR #3878 submitted. While I could just reproduce the case that headers is null but could not reproduce the AMQP.BasicProperties is null, so I add null check for them all.

**Comment by Xylus** [comment] 2018-03-05 05:28
@jiaqifeng Thanks. Providing a safeguard for both cases looks like a good solution.

**Comment by geekMessi** [comment] 2018-03-06 03:36
@jiaqifeng 
Wonderful! This will work better.

**Comment by Xylus** [comment] 2018-03-08 07:04
resolved via #3878

**Closed by Xylus** 2018-03-08 07:04 UTC
Labels: bug, module:plugin
