### ISSUE TITLE
agent pinpoint lost in webui

### ISSUE THREAD

**Issue by chris93111** [naver/pinpoint#3914] opened 2018-03-19 13:48 UTC
hello 

i have infra pinpoint in openshift and sometime when i configue or work the network  , 
i lost agent in webui , is needed to reboot process java for work again 

it's possible to configure agent for not stop after error network request ?

pinpoint verson 1.7.1 

Log : 

2018-03-19 11:43:51 [INFO ](.n.p.r.c.PinpointClientHandlerState) DefaultPinpointClientHandler@1157afa0 stateTo() completed. Socket state change success(updateWanted:RUN_DUPLEX ,before:RUN_WITHOUT_HANDSHAKE ,current:RUN_DUPLEX).
2018-03-19 11:43:51 [INFO ](.p.r.c.DefaultPinpointClientHandler) [id: 0xeb5cd745, /10.210.14.8:38490 => /10.210.6.46:9994] handleHandshakePacket() completed. code:DUPLEX_COMMUNICATION
2018-03-19 11:44:02 [INFO ](c.n.p.p.s.UdpDataSender            ) packet send error. size:668, TAgentStatBatch(agentId:registry-c, startTimestamp:1521235920061, agentStats:[TAgentStat(agentId:registry-c, startTimestamp:1521235920061, timestamp:1521456217728, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:66630256, jvmMemoryHeapMax:253427712, jvmMemoryNonHeapUsed:123919928, jvmMemoryNonHeapMax:-1, jvmGcOldCount:5, jvmGcOldTime:967), cpuLoad:TCpuLoad(jvmCpuLoad:0.012096774193548387, systemCpuLoad:0.02620967741935484), transaction:TTransaction(sampledNewCount:8, sampledContinuationCount:0, unsampledNewCount:8, unsampledContinuationCount:0), activeTrace:TActiveTrace(histogram:TActiveTraceHistogram(version:0, histogramSchemaType:2, activeTraceCount:[0, 0, 0, 0])), dataSourceList:TDataSourceList(dataSourceList:[]), responseTime:TResponseTime()), TAgentStat(agentId:registry-c, startTimestamp:1521235920061, timestamp:1521456222728, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:72913728, jvmMemoryHeapMax:253427712, jvmMemoryNonHeapUsed:123918136, jvmMemoryNonHeapMax:-1, jvmGcOldCount:5, jvmGcOldTime:967), cpuLoad:TCpuLoad(jvmCpuLoad:0.020161290322580645, systemCpuLoad:0.036290322580645164), transaction:TTransaction(sampledNewCount:19, sampledContinuationCount:0, unsampledNewCount:19, unsampledContinuationCount:0), activeTrace:TActiveTrace(histogram:TActiveTraceHistogram(version:0, histogramSchemaType:2, activeTraceCount:[0, 0, 0, 0])), dataSourceList:TDataSourceList(dataSourceList:[]), responseTime:TResponseTime()), TAgentStat(agentId:registry-c, startTimestamp:1521235920061, timestamp:1521456227728, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:47747152, jvmMemoryHeapMax:253427712, jvmMemoryNonHeapUsed:123923520, jvmMemoryNonHeapMax:-1, jvmGcOldCount:5, jvmGcOldTime:967), cpuLoad:TCpuLoad(jvmCpuLoad:0.02620967741935484, systemCpuLoad:0.04032258064516129), transaction:TTransaction(sampledNewCount:13, sampledContinuationCount:0, unsampledNewCount:13, unsampledContinuationCount:0), activeTrace:TActiveTrace(histogram:TActiveTraceHistogram(version:0, histogramSchemaType:2, activeTraceCount:[0, 0, 0, 0])), dataSourceList:TDataSourceList(dataSourceList:[]), responseTime:TResponseTime()), TAgentStat(agentId:registry-c, startTimestamp:1521235920061, timestamp:1521456232728, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:51004432, jvmMemoryHeapMax:253427712, jvmMemoryNonHeapUsed:123929808, jvmMemoryNonHeapMax:-1, jvmGcOldCount:5, jvmGcOldTime:967), cpuLoad:TCpuLoad(jvmCpuLoad:0.01616161616161616, systemCpuLoad:0.06464646464646465), transaction:TTransaction(sampledNewCount:11, sampledContinuationCount:0, unsampledNewCount:11, unsampledContinuationCount:0), activeTrace:TActiveTrace(histogram:TActiveTraceHistogram(version:0, histogramSchemaType:2, activeTraceCount:[0, 0, 0, 0])), dataSourceList:TDataSourceList(dataSourceList:[]), responseTime:TResponseTime()), TAgentStat(agentId:registry-c, startTimestamp:1521235920061, timestamp:1521456237728, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:55116760, jvmMemoryHeapMax:253427712, jvmMemoryNonHeapUsed:123929808, jvmMemoryNonHeapMax:-1, jvmGcOldCount:5, jvmGcOldTime:967), cpuLoad:TCpuLoad(jvmCpuLoad:0.01609657947686117, systemCpuLoad:0.03219315895372234), transaction:TTransaction(sampledNewCount:19, sampledContinuationCount:0, unsampledNewCount:18, unsampledContinuationCount:0), activeTrace:TActiveTrace(histogram:TActiveTraceHistogram(version:0, histogramSchemaType:2, activeTraceCount:[0, 0, 0, 0])), dataSourceList:TDataSourceList(dataSourceList:[]), responseTime:TResponseTime()), TAgentStat(agentId:registry-c, startTimestamp:1521235920061, timestamp:1521456242728, collectInterval:5000, gc:TJvmGc(type:SERIAL, jvmMemoryHeapUsed:57769656, jvmMemoryHeapMax:253427712, jvmMemoryNonHeapUsed:123929808, jvmMemoryNonHeapMax:-1, jvmGcOldCount:5, jvmGcOldTime:967), cpuLoad:TCpuLoad(jvmCpuLoad:0.012096774193548387, systemCpuLoad:0.04435483870967742), transaction:TTransaction(sampledNewCount:12, sampledContinuationCount:0, unsampledNewCount:12, unsampledContinuationCount:0), activeTrace:TActiveTrace(histogram:TActiveTraceHistogram(version:0, histogramSchemaType:2, activeTraceCount:[0, 0, 0, 0])), dataSourceList:TDataSourceList(dataSourceList:[]), responseTime:TResponseTime())])
java.net.PortUnreachableException: ICMP Port Unreachable
        at java.net.PlainDatagramSocketImpl.send(Native Method)
        at java.net.DatagramSocket.send(Unknown Source)
        at com.navercorp.pinpoint.profiler.sender.UdpDataSender.sendPacket(UdpDataSender.java:134)
        at com.navercorp.pinpoint.profiler.sender.AbstractDataSender$1.execute(AbstractDataSender.java:68)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:172)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.doExecute(AsyncQueueingExecutor.java:96)
        at com.navercorp.pinpoint.profiler.sender.AsyncQueueingExecutor.run(AsyncQueueingExecutor.java:79)
        at java.lang.Thread.run(Unknown Source)
2018-03-19 11:44:50 [INFO ](c.n.p.r.c.PinpointClientHandshaker ) PinpointClientHandshaker@7c542d73 HandshakeJob completed.

**Comment by koo-taejin** [comment] 2018-03-20 00:47
hi chris93111

I think the issue is related to # 3827, # 3733.
1.7.2 will be released,  then please use 1.7.2 and report it again if you keep having problems.

thanks.

**Closed** 2018-04-02 05:26 UTC

**Comment by aviranmz** [comment] 2019-02-28 11:08
@chris93111 - what OC did you used?

**Comment by chris93111** [comment] 2019-02-28 12:33
Hi @aviranmz is origin 3.7
