### ISSUE TITLE
Kafka plugin, multiple consumer issue, UI/spanId related.

### ISSUE THREAD

**Issue by yjqg6666** [naver/pinpoint#7212] opened 2020-09-03 04:21 UTC
#### Prerequisites
- [x]  I have checked the [FAQ](http://naver.github.io/pinpoint/faq.html), and [issues](https://github.com/naver/pinpoint/issues) and found no answer.

#### What version of pinpoint are you using?
2.0.4

#### Describe the bug
When one app send a kafka message triggered by a http request, multiple apps consume the same message and process the message, then these apps make another http request to a http service. The whole thing could be described as the following server map **(two outbounds)**.
![image](https://user-images.githubusercontent.com/1879641/92067881-fe64ec80-edd7-11ea-8282-f29f8a6118c7.png)

issue 1:
The main server map could not show correctly(the consumer node could be omitted or linked) when **one outbound** is chosen as the screenshot below.

![image](https://user-images.githubusercontent.com/1879641/92068033-64517400-edd8-11ea-9a6b-a1b3b7474fce.png)

issue 2:
The app consumer-verify1, consumer-verify2 and consumer-verify3 each called verify-http-server-dev. They all should be linked to the verify-http-server-dev node and the call counts should be 1 for each.
![image](https://user-images.githubusercontent.com/1879641/92070139-df695900-eddd-11ea-8990-45aa072279b3.png)

The server map for this transaction should look like the following:

![image](https://user-images.githubusercontent.com/1879641/92373745-6184b500-f131-11ea-9bb2-fa5db9ff7022.png)

![image](https://user-images.githubusercontent.com/1879641/92070589-03796a00-eddf-11ea-8e32-219d1e90f8db.png)

The request headers:

verify1 -> http-server
```
GET /api/verify1?seq=msg_1599102848086 HTTP/1.0
Host: verify.example.com
Connection: close
User-Agent: Apache-HttpClient/4.3.6 (java 1.5)
Accept-Encoding: gzip,deflate
Pinpoint-TraceID: pub-loc1^1599102239212^2
Pinpoint-SpanID: 109811431385031189
Pinpoint-pSpanID: 6902915841584694206
Pinpoint-Flags: 0
Pinpoint-pAppName: consumer-verify1
Pinpoint-pAppType: 1210
Pinpoint-Host: verify.example.com
```

verify2 -> http-server
```
GET /api/verify2?seq=msg_1599102848086 HTTP/1.0
Host: verify.example.com
Connection: close
User-Agent: Apache-HttpClient/4.3.6 (java 1.5)
Accept-Encoding: gzip,deflate
Pinpoint-TraceID: pub-loc1^1599102239212^2
Pinpoint-SpanID: 4440757486945348215
Pinpoint-pSpanID: 6902915841584694206
Pinpoint-Flags: 0
Pinpoint-pAppName: consumer-verify2
Pinpoint-pAppType: 1210
Pinpoint-Host: verify.example.com

```
verify3 -> http-server 
```
GET /api/verify3?seq=msg_1599102848086 HTTP/1.0
Host: verify.example.com
Connection: close
User-Agent: Apache-HttpClient/4.3.6 (java 1.5)
Accept-Encoding: gzip,deflate
Pinpoint-TraceID: pub-loc1^1599102239212^2
Pinpoint-SpanID: -1471803627387986967
Pinpoint-pSpanID: 6902915841584694206
Pinpoint-Flags: 0
Pinpoint-pAppName: consumer-verify3
Pinpoint-pAppType: 1210
Pinpoint-Host: verify.example.com

```

They all had the same Pinpoint-pSpanID but got different Pinpoint-pAppName. The Pinpoint-pSpanIDs should be different.

**Comment by yjqg6666** [comment] 2020-09-03 05:27
The main server map got this issue when there is only one consumer.
![image](https://user-images.githubusercontent.com/1879641/92074602-0b3e0c00-ede9-11ea-95f9-3e1114997334.png)

**Comment by yjqg6666** [comment] 2020-09-03 05:31
The web side got these logs.
> 2020-09-03 13:29:40 [WARN ](c.n.p.w.s.m.VirtualLinkMarker      ) one to N replaced. node:verify-pub(STAND_ALONE:1000)->host:kafka.example.com:9092 accept:[AcceptApplication{host='kafka.example.com:9092', application=consumer-verify1(SPRING_BOOT:1210)}, AcceptApplication{host='kafka.example.com:9092', application=kafka.example.com:9092(KAFKA_CLIENT:8660)}]
> 2020-09-03 13:29:40 [ERROR](c.n.p.w.s.m.VirtualLinkHandler     ) targetLinkData not found findLinkKey:LinkKey{fromApplication='verify-pub', fromServiceType=STAND_ALONE, toApplication='consumer-verify1', toServiceType=SPRING_BOOT, hash=870137464}

**Comment by yjqg6666** [comment] 2020-09-03 05:36
The config for the kafka plugin:

> profiler.kafka.producer.enable=true
> profiler.kafka.consumer.enable=true
> profiler.springkafka.consumer.enable=true
> profiler.kafka.consumer.entryPoint=

**Comment by koo-taejin** [comment] 2020-09-03 05:46
hi @yjqg6666 

In my guessing, this is probably due to that Queue is a virtual node.
When draws Servermap,  it is expected that the application after the queue will be included, because Queue is a virtual node, it is not included as depth,
In this case, since the line is limited by the depth, it is assumed that it is not drawn together and only the nodes that has no connection are expressed .

This is my guess, and the exact problem seems to need analysis.

thanks :)

**Comment by yjqg6666** [comment] 2020-09-03 05:57
@koo-taejin thanks for the quick reply. How about the second one? The pSpanID may came from the kafka header and used for three different applications. I think it's a hard-to-solve issue. How about replace with new spanIds on the web side?

**Comment by koo-taejin** [comment] 2020-09-03 07:44
@yjqg6666 
The queue type is a little different from the original design, and there are a little problem in processing the queue type.
I will also consider it. 

Thanks for your reporting

**Comment by yjqg6666** [comment] 2020-09-07 01:14
@koo-taejin Should i keep this issue open or close it.

**Comment by koo-taejin** [comment] 2020-09-07 05:39
@yjqg6666 
Please keep this issue with open state 

thanks :)

**Comment by yjqg6666** [comment] 2020-09-07 08:52
**I just got a workaround.**  In the kafka plugin when it consume a record, I tried to save the Pinpoint-SpanID in a ConsumerRecord header as an annotation and generate a new span id for the consumer. In the web when construct a call tree and if the service type of a span is queue(i only check if it's kafka), i restore the span id from the previous-set annotation value. It's working in the call tree and servermap.  It's not a good way but hopefully it may have some help.
Hopefully there would be a better official solution for the queue type(one-to-many).

**Comment by koo-taejin** [comment] 2020-09-08 00:07
@yjqg6666 

Thank you so much for giving me a great idea.

If it is possible, could you send me your work to PR?
Let me test it and see if there are any something that I have to care about.

thanks :)

**Comment by yjqg6666** [comment] 2020-09-08 02:05
@koo-taejin I just sent a PR.

**Comment by yjqg6666** [comment] 2020-09-08 02:08
In the PR,  the web side contains some specific code for Kafka-only, it's not a good solution. There should be a better /general solution for the queues.

**Comment by koo-taejin** [comment] 2020-09-21 07:45
@yjqg6666 

I let you know progression of this issue. 

I am looking to solve problem 1.

The cause seems to be the wrong EndPoint.
Kafka client acts as a server, but it is a client. 
Besides, Kafka client kept everything in isolation, making it difficult to obtain this information.
So it has difficult to get the EndPoint.

There seems to be a problem with trying to handle it well without EndPoint, because it was too difficult to get the correct EndPoint with Stably.
I have been trying to dig in Kafka structure to solve it. 

I am thinking of getting EndPoint at Kafka Selector.

So, If I find out good solution, then I will commit it. 

thanks :)

**Comment by koo-taejin** [comment] 2020-09-23 00:06
@yjqg6666 

I expected to have solved issue 1 via #7283 

Could you check whether this issue has solved or not?

thanks :)

**Comment by yjqg6666** [comment] 2020-09-23 01:13
@koo-taejin I am building the master now and will check and update soon.

**Comment by yjqg6666** [comment] 2020-09-23 01:39
@koo-taejin Checked and have confirmed that the first issue is fixed. Thumb up!

The topic-publish app:

![image](https://user-images.githubusercontent.com/1879641/93954452-557b3300-fd80-11ea-8f75-5354e68018ad.png)


The topic-consume app:

![image](https://user-images.githubusercontent.com/1879641/93954474-6166f500-fd80-11ea-94bb-4e673671d440.png)


The topic-publish app(inbound-1 and outbound-2):

![image](https://user-images.githubusercontent.com/1879641/93954517-7e9bc380-fd80-11ea-9505-8ab02c2728aa.png)

**Comment by koo-taejin** [comment] 2020-09-23 01:54
@yjqg6666 

I am glad to hear that. 
I try to be thinking of solve issue 2 from now. 

If I have any progression, then I am going to share with you. 

thanks :)

**Comment by koo-taejin** [comment] 2020-09-23 06:48
@yjqg6666 

Can you check the issue 2 using the master branch?

As a result of analysis, it is expected that the information of callerHost has been changed due to the changed endPoint, so it will come out normally.

If the results come out, please share 

thanks :)

**Comment by yjqg6666** [comment] 2020-09-23 07:08
> @yjqg6666
> 
> Can you check the issue 2 using the master branch?
> 
> As a result of analysis, it is expected that the information of callerHost has been changed due to the changed endPoint, so it will come out normally.
> 
> If the results come out, please share
> 
> thanks :)

checking.

**Comment by yjqg6666** [comment] 2020-09-23 07:56
@koo-taejin not working.

It should be:

![image](https://user-images.githubusercontent.com/1879641/93983435-229f6200-fdb5-11ea-8f7c-1a376aea17ff.png)

Now still get this one using master:
![image](https://user-images.githubusercontent.com/1879641/93983498-38148c00-fdb5-11ea-8c9f-6a075323e98c.png)

**Comment by koo-taejin** [comment] 2020-09-23 08:03
@yjqg6666 
Does the above appear in the main server map instead of the server map in CallStack?
I thought the Main server map would have been solved because it draws the server map base on caller and callee tables.

**Comment by koo-taejin** [comment] 2020-09-23 08:37
@yjqg6666 
It is judged that it works well if I make reproducing situation.
Is there any doubt that it is different from the part that I made?

* servermap in main
![my2](https://user-images.githubusercontent.com/10057874/93988136-56818400-fdc3-11ea-8909-7f8a755a2177.png)

* servermap in callstack
![my1](https://user-images.githubusercontent.com/10057874/93988093-4b2e5880-fdc3-11ea-9e63-b1eb19790c15.png)

**Comment by yjqg6666** [comment] 2020-09-23 09:09
@koo-taejin It's fixed in the main server map. Now the issue only exist in the server map for a single transaction and only if the consumer apps both/all then all the same other app.
In you case tj-testweb2 and tj-testweb3 both call tj-testweb4.

**Comment by yjqg6666** [comment] 2020-09-23 09:11
This is the main server map:
![image](https://user-images.githubusercontent.com/1879641/93992102-b9711c00-fdbf-11ea-9564-975fc4265e8f.png)

**Comment by yjqg6666** [comment] 2020-09-23 09:14
In your case tj-testweb2 do not call tj-testweb4 and can not see the issue. If called the call num between tj-testweb2/tj-testweb3 and tj-testweb4 should be 2 instead of 1.
![image](https://user-images.githubusercontent.com/1879641/93992261-ec1b1480-fdbf-11ea-8bef-d1b7ed23fe0d.png)

**Comment by koo-taejin** [comment] 2020-09-23 09:21
@yjqg6666 

I have understood that what you mean. 
Thanks for your detailed explanation.

**Comment by koo-taejin** [comment] 2020-09-24 05:01
@yjqg6666 

I let you know progression of this issue 2.

I have found out reason of this issue and the way I solve this issue. 
I am working on finding, if this solution has another problem. 
If I am sure that it has not any problem, then I am going to commit it. 

thanks :)

**Comment by koo-taejin** [comment] 2020-09-24 23:44
@yjqg6666 

I expected to have solved issue 2 via #7290

Could you check whether this issue has solved or not?

thanks :)

**Comment by yjqg6666** [comment] 2020-09-25 05:31
> I expected to have solved issue 2 via #7290
> Could you check whether this issue has solved or not?


checking.

**Comment by yjqg6666** [comment] 2020-09-25 06:06
@koo-taejin Now it works like a charm.

**Comment by koo-taejin** [comment] 2020-09-25 07:46
@yjqg6666 
I am glad to hear that.

Please close this issue, If you do not have any problem. 

thanks :)

**Closed** 2020-09-25 08:28 UTC
Labels: bug, module:web
